language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - "node_modules"

after_success:
  - docker build --tag configuration:1.0.0 .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/configuration:1.0.0
