language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - "node_modules"

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build . --tag "ivandelabeldad/private:1.0.0"
  - docker push "ivandelabeldad/private:1.0.0"
