version: '3.4'
services:
  api:
    image: ivandelabeldad/rackian_api:1.0.0
    build:
      context: .
      args:
      - PORT
    ports:
    - $PORT:$PORT
    environment:
    - DB_URI
    - DB_NAME
    - PORT
